apiVersion: v1
kind: Secret
metadata:
  name: banka-app-secrets
  namespace: banka-1
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  USER_SERVICE_DB_USER: postgres
  USER_SERVICE_DB_PASSWORD: postgres
  BANKING_CORE_DB_USER: postgres
  BANKING_CORE_DB_PASSWORD: postgres
  MARKET_SERVICE_DB_USER: postgres
  MARKET_SERVICE_DB_PASSWORD: postgres
  TRADING_DB_USER: postgres
  TRADING_DB_PASSWORD: postgres
  CREDIT_DB_USER: postgres
  CREDIT_DB_PASSWORD: postgres
  INTERBANK_DB_USER: postgres
  INTERBANK_DB_PASSWORD: postgres
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: guest
  JWT_SECRET: change-me-before-prod
  TWELVE_DATA_API_KEY: ""
  ALPHA_VANTAGE_API_KEY: ""
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  BANKA2_INBOUND_TOKEN: dev-inbound-banka2-to-banka1
  BANKA2_OUTBOUND_TOKEN: dev-outbound-banka1-to-banka2
